// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaL_Mfhd_KbKkoOlZz9s51sLJTO1Y33dw',
    appId: '1:662631923682:web:cee67cf8c08283c1ec03bb',
    messagingSenderId: '662631923682',
    projectId: 'shopping-e1c1b',
    authDomain: 'shopping-e1c1b.firebaseapp.com',
    storageBucket: 'shopping-e1c1b.appspot.com',
    measurementId: 'G-9NWPTT0G5J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8guAbwesuZ2YQ-XhgnoIadW0GngZOAE4',
    appId: '1:662631923682:android:cd57561e97f90045ec03bb',
    messagingSenderId: '662631923682',
    projectId: 'shopping-e1c1b',
    storageBucket: 'shopping-e1c1b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCurEFqNMYVXR4lTU-DKa14mnaRTgYwLOs',
    appId: '1:662631923682:ios:59eb6c392084ed06ec03bb',
    messagingSenderId: '662631923682',
    projectId: 'shopping-e1c1b',
    storageBucket: 'shopping-e1c1b.appspot.com',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCurEFqNMYVXR4lTU-DKa14mnaRTgYwLOs',
    appId: '1:662631923682:ios:10be43232f3cbf3eec03bb',
    messagingSenderId: '662631923682',
    projectId: 'shopping-e1c1b',
    storageBucket: 'shopping-e1c1b.appspot.com',
    iosBundleId: 'com.example.ecommerceApp.RunnerTests',
  );
}
